//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMTT.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Artists_Categories
    {
        [DataMember]
        public int IdArtist { get; set; }
        [DataMember]
        public int IdCategory { get; set; }
        [DataMember]
        public string Observation { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Category Category { get; set; }
    }
}
